name: Build & Push to Docker Hub

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagen a Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: kalemat/04-eliminar-pedido:latest
